# Generated by Django 3.2.8 on 2022-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_pharmacy_amount_remove_pharmacy_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='docOnDuty',
            field=models.CharField(choices=[('Doc Ben', 'Doc Ben'), ('Doc Mike', 'Doc Mike'), ('Doc Seun', 'Doc Seun'), ('Doc Peter', 'Doc Peter')], default='Doc Ben', max_length=30, verbose_name='Genotype'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nurseOnDuty',
            field=models.CharField(choices=[('Nurse Hannah', 'Nurse Hannah'), ('Nurse Yinka', 'Nurse Yinka'), ('Nurse Zainab', 'Nurse Zainab'), ('Nurse Betty', 'Nurse Betty')], default='Nurse Hannah', max_length=39, verbose_name='Genotype'),
        ),
    ]
