# Generated by Django 3.2.8 on 2022-08-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220828_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='nurse',
        ),
    ]
